trigger:
- master
resources:
- repo: self
variables:
 dockerRegistryServiceConnection: 'a74a987a-87e2-486f-92af-7baf221c7033'
  tag: '$(Build.BuildId)'
stages:
- stage: Build
  displayName: Build and Push image
  jobs:
   - job: Build
     displayName: Build and Push
     pool:
        vmImage: 'ubuntu-latest'
     steps:
      - task: Docker@2
        inputs:
           containerRegistry: 'dockerRegistryServiceConnection'
           repository: 'pskitsme92/TestAutomation'
           command: 'buildAndPush'
           Dockerfile: '**/Dockerfile'
      - task: CopyFiles@2
        inputs:
           Contents: 'docker-compose.yml'
           TargetFolder: '$(dBuild.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
           PathtoPublish: '$(Build.ArtifactStagingDirectory)'
           ArtifactName: 'drop'
           publishLocation: 'Container'